dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm run reinstall

script:
  - karma start --single-run --browsers ChromeHeadless,FirefoxHeadless